fix: Upgrade pouch-link
cozy/cozy-drive pull request #2425
Opened 2021-09-06 10:01 UTC by paultranvan

To get a fix for Pouch migration

2021-09-06 12:42 UTC, JF-Cozy commented on package.json
> +    "cozy-pouch-link": "^24.3.1",
version fixe ?

2021-09-07 13:27 UTC, JF-Cozy approved these changes

2021-09-07 13:29 UTC, Crash-- requested changes
branche de release en cours qui sera mergée plus tard

2022-01-28 15:55 UTC, trollepierre commented
I think this PR can be close, isn't it @paultranvan ?

2022-01-28 16:16 UTC, closed without merging